---
- name: Remove nginx
  apt: name=nginx state=absent

- name: Install Apache2 and PHP
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-php

- name: Disable Apache2 Modules
  apache2_module: name={{ item }} state=absent force=true
  with_items:
    - mpm_event
    - mpm_worker

- name: Enable Apache2 mpm_prefork
  apache2_module: name={{ item }} state=present force=true
  with_items:
    - mpm_prefork

- name: Enable Apache2 Modules
  apache2_module: name={{ item }} state=present 
  with_items:
    - php7.0
    - rewrite

- name: Check that Apache is Running
  service: name=apache2 state=running
