---
- name: Remove nginx
  apt: name=nginx state=absent

- name: Install Apache2 and PHP
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-php

- name: Try to Enable Apache2 mpm_prefork
  shell: a2dismod mpm_worker && a2dismod mpm_event && a2enmod mpm_prefork
# an ugly hack, but a2enmod state management messes up the first time

- name: Enable Apache2 Modules
  apache2_module: name={{ item }} state=present 
  with_items:
    - mpm_prefork
    - php7.0
    - rewrite

- name: Check that Apache is Running
  service: name=apache2 state=started
